### ISSUE TITLE
More layout options

### ISSUE THREAD

**Issue by xTomsko** [kelvinhall05/Southpaw75#2]
Hey is it possible that the pcb and plate can be updated so it supports split backspace, Tsangang bottom row and split r-shift? 
I am a big fan of this project, but this was something I was always wondering about!

**Comment by kelvinhall05** [comment]
This would require a significant amount of reworking that I am not interested in doing myself, and I wouldn't feel comfortable publishing files to something I have not purchased and tested, which I am absolutely not interested in doing.

If you'd like to see these changes made, feel free to fork and make them yourself, order and test the board, fix any issues that arise, and then open a pull request.

**Comment by charlie-hotel** [comment]
press F to pay for it this time
